services:
  postgres-test:
    image: postgres:16
    container_name: motel_test_db
    ports:
      - "5433:5432" # Porta diferente da oficial (5432) para n√£o dar conflito
    environment:
      POSTGRES_DB: motel_test_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    restart: always
